package com.enactor.pos.mobile.web;

/**
 * An interface responsible for interacting with logical devices using Appium in a
 * mobile automation context. This interface defines methods for performing actions
 * such as entering text, pressing buttons, checking device status, retrieving receipt
 * text, and clearing printer data.
 * 
 * @author Preminda.Bandara
 */
public interface ILogicalDeviceStepProvider {
	
    /**
     * Sends a text input command to a specified logical device window.
     * 
     * @param text       The text to be entered.
     * @param windowName The name of the logical device window.
     */
    public void enterTextOnDevice(String text, String windowName);

    /**
     * Sends a button press command to a specified logical device window.
     * 
     * @param actionButton The action or button to be pressed.
     * @param windowName   The name of the logical device window.
     */
    public void pressButtonOnDevice(String actionButton, String windowName);
    
    /**
     * Checks the status of a specified logical device window within a given time.
     * 
     * @param windowName The name of the logical device window.
     * @param time       The maximum time to wait for the check.
     */
    public void checkDevice(String windowName, long time);
    
    /**
     * Retrieves the text from the receipt generated by the logical printer device.
     * 
     * @return The text content of the receipt as a String.
     */
    public String getReceiptText();
    
    /**
     * Clears the logical printer device, removing any stored data or pending print jobs.
     */
    public void clearPrinter();
    
	public void selectComboboxItem(String testData, String componentId, String windowId);
}