#########################################################################
# TRUNK test data
#########################################################################

# POS details
# -----------
TERMINAL_NUMBER=201
LOCATION=Enactor Store

# Login details
# -------------
MANAGER_USERNAME=3005
MANAGER_PASSWORD=3005
MANAGER_NAME=Manager

# Manager having Associates
# -------------------------
MANAGER_2_USERNAME=m1
MANAGER_2_PASSWORD=m1
MANAGER_2_NAME=Manager - UK 1
MANAGER_2_EMAIL=enactor.test@gmail.com

SUPERVISOR_USERNAME=3002
SUPERVISOR_PASSWORD=3002
SUPERVISOR_NAME=Supervisor
SALES_ASSISTANT_USERNAME=1010
SALES_ASSISTANT_PASSWORD=1010
SALES_ASSISTANT_NAME=Michael Browne
FISCAL_SALES_ASSISTANT_USERNAME=0251
FISCAL_SALES_ASSISTANT_PASSWORD=0251

# Employee details
# ----------------
EMPLOYEE_1_ID=1
EMPLOYEE_1_NAME=Mr Sam Granger

# Customer details
# ----------------
CUSTOMER_1_NAME=Mark
CUSTOMER_1_FULL_NAME=Mr Mark Harrison
CUSTOMER_1_SEX=Male
CUSTOMER_1_DOB=28/08/79
CUSTOMER_1_EMAIL=demo@enactor.co.uk
CUSTOMER_1_PHONE_NO=01295768256
CUSTOMER_1_LOYALTY_NO=9526300011110240001

# Products details
# ----------------
PRODUCT_1=1
PRODUCT_1_DESCRIPTION=KAT VON D Eye Liner
PRODUCT_1_PRICE=£18.00
PRODUCT_1_PROMOTION=£3 off of KAT VON D Eye Liner
PRODUCT_2=2
PRODUCT_2_DESCRIPTION=HD Complexion Starter Kit
PRODUCT_2_PRICE=£12.00
PRODUCT_3=A-1
PRODUCT_3_DESCRIPTION=A-1
PRODUCT_3_PRICE=£5.00
PRODUCT_4=579490
PRODUCT_4_DESCRIPTION=CLINIQUE Exfoliating Scrub
PRODUCT_4_PRICE=£19.50
PRODUCT_4_PROMOTION=£3.50 off of Clinque Brand
PRODUCT_5=1595461
PRODUCT_5_DESCRIPTION=Amazing Grace Gift Set
PRODUCT_5_PRICE=£55.00
PRODUCT_5_PROMOTION=20% Off Of all Perfume Gift Sets
PRODUCT_FISCAL_1=1001000
PRODUCT_FISCAL_1_DESCRIPTION=Duvet lock NELLIE 16pcs/pack
PRODUCT_FISCAL_2=1259680
PRODUCT_FISCAL_2_DESCRIPTION=DCS NELL Sateen SGL black KRON
PRODUCT_FISCAL_3=1048900
PRODUCT_FISCAL_3_DESCRIPTION=Ingen dansk beskrivelse
PRODUCT_FISCAL_4=1050201
PRODUCT_FISCAL_4_DESCRIPTION=Ingen dansk beskrivelse

#This must be comma separated list
PRODUCT_LIST=1,2

# Style Colour Size Product
# -------------------------
STYLE_COLOUR_SIZE_PRODUCT_1=1379692
STYLE_COLOUR_SIZE_PRODUCT_1_PRICE=£12.00
STYLE_COLOUR_SIZE_PRODUCT_1_DESCRIPTION=HD Complexion Starter Kit
STYLE_COLOUR_SIZE_PRODUCT_1_LONG_DESCRIPTION=An essential kit for achieving a flawless, high-definition complexion in three simple steps.
STYLE_COLOUR_SIZE_PRODUCT_1_EXTENDED_DESCRIPTION=This set contains:\n- 0.17 oz HD Microfinish Powder\n- 0.5 oz HD Microperfecting Primer\n- 1.01 oz HD Invisible Cover Foundation\n- HD Kabuki Brush
STYLE_COLOUR_SIZE_PRODUCT_1_COLOUR_2=Pink Undertone
STYLE_COLOUR_SIZE_PRODUCT_1_SIZE_2=2

# Style Colour Size Product
# -------------------------
MERCHANDISE_PRODUCT_1=942086
MERCHANDISE_PRODUCT_1_PRICE=£20.00
MERCHANDISE_PRODUCT_1_DESCRIPTION=Smashbox Photo Op
MERCHANDISE_PRODUCT_1_LONG_DESCRIPTION=A brush-on undereye brightening cream.
MERCHANDISE_PRODUCT_1_EXTENDED_DESCRIPTION=Photo shoots often start early in the morning when models and celebs aren't quite looking their best, but those dark circles are now a thing of the past! With this lightweight brightener, you'll be camera ready in no time! It works to make you look your best so you'll be prepared for any photo opportunity that pops up!

# Gift Cards
#-----------
INVALID_GIFT_CARD_NUMBER=INVALID
# New Gift Card # (delete the card from EM after test)
GIFT_CARD_NUMBER_1=9526300100010001253
# Gift Card # for enquiry  
GIFT_CARD_NUMBER_2=9526300100010001112
# Gift Card not exists in EM
GIFT_CARD_NUMBER_3=9526300100010001257

# RETRUN
#--------
COMPLETE_RECEIPT_RETURN_NOT_WANTED=Not Wanted (10 Days)
COMPLETE_RECEIPT_RETURN_DAMAGED=Damaged \/ Faulty (No date limit)
RETURN_TENDER_CASH_UK=Cash UK

# Loyalty
#---------
LOYALTY_CARD_NUMBER_1=9526300011110240001
LOYALTY_CARD_NUMBER_1_FORNAME=Mark
LOYALTY_CARD_NUMBER_1_SURNAME=Harrison
LOYALTY_CARD_NUMBER_1_FULL_NAME=Mr Mark Harrison
LOYALTY_CARD_NUMBER_1_ACCOUNT_NUMBER=1
LOYALTY_CARD_NUMBER_1_LOYALTY_SCHEME=Loyalty Scheme 1 UK
LOYALTY_CARD_NUMBER_1_ACCOUNT_STATUS=Active
LOYALTY_CARD_NUMBER_1_LOYALTY_TIER=Gold
LOYALTY_CARD_NUMBER_1_BALANCE=0
LOYALTY_CARD_NUMBER_1_POINT_RATE=100
LOYALTY_CARD_NUMBER_1_TRANSACTION_POINTS_EARNED=25
LOYALTY_CARD_NUMBER_2=9526300311110240010
LOYALTY_CARD_NUMBER_2_LOYALTY_SCHEME=Loyalty Scheme 1 UK
LOYALTY_CARD_NUMBER_2_LOYALTY_TIER=Silver

# Report
#-------
REPORT_YEAR=2019
MONTH_REPORT=February
PERIOD_REPORT=2

# Transaction ID
#-----------
TRANSACTION_ID=

# Test Run Time
#-----------
TEST_RUN_TIME=



