#########################################################################
# Enactor Mobile POS Configuration File
############################### ##########################################
STEPS_PROVIDER_CLASS_NAME=com.enactor.pos.mobile.MobileThinClientPosStepsProvider
COMPONENT_CRM_DIARY_APPOINTMENT_START_TIME_HOURS=PAGE_PANEL.BORDER_PANEL.PANEL_1.DATE_PANEL.PANEL_3.START_TIME.HOUR_TEXT_FIELD
COMPONENT_CRM_DIARY_APPOINTMENT_END_TIME_HOURS=PAGE_PANEL.BORDER_PANEL.PANEL_1.DATE_PANEL.PANEL_3.END_TIME.HOUR_TEXT_FIELD
COMPONENT_CRM_DIARY_APPOINTMENT_START_TIME_MINUTES=PAGE_PANEL.BORDER_PANEL.PANEL_1.DATE_PANEL.PANEL_3.START_TIME.MINUTE_TEXT_FIELD
COMPONENT_CRM_DIARY_APPOINTMENT_END_TIME_MINUTES=PAGE_PANEL.BORDER_PANEL.PANEL_1.DATE_PANEL.PANEL_3.END_TIME.MINUTE_TEXT_FIELD
