WINDOW_ENTER_USER=Point-of-Sale Application:Point-of-Sale Application:Enter User  Native/NextGen/Pos/SignOn/SignOn  EnterUserState  NextGen1024x768/Pos/SignOn/EnterUser
WINDOW_ENTER_USER_INVALID_ERROR=\  Native/NextGen/Pos/SignOn/SignOn  InvalidUserPin  NextGen1024x768/Error/Error
WINDOW_ENTER_USER_INVALID_ERROR_2=\  Native/NextGen/Pos/SignOn/SignOn  InvalidUserPin2  NextGen1024x768/Error/Error
WINDOW_ENTER_USER_REQUIRED_ERROR=\  Native/NextGen/Pos/SignOn/SignOn  UserIdRequired  NextGen1024x768/Error/Error
WINDOW_CONFIRM_EXIT=\  Native/NextGen/Pos/SignOn/SignOn  ConfirmExit  NextGen1024x768/Message/PopUpModalYesNo
WINDOW_ENTER_USER_AFTER_SCAN=\  Native/NextGen/Pos/SignOn/SignOn  EnterPinState  NextGen1024x768/Pos/SignOn/EnterPinSignOn
