#LoginDetails
valid.username=admin
valid.password=admin
valid.device.id=estateManager.enactor

test.user=testadmin
special.admin.username=
special.admin.password=
device.id=estateManager.enactor
source.id=POS-TN:0001
store.manager.1.username=storemanager
store.manager.1.password=storemanager123
operational.admin.username=OPERATIONAL_ADMIN
operational.admin.password=3edc4rfv$R
em.user.1.username=hamza.naleer
em.user.1.password=sladRbd7jr
manager.1.username=m1
manager.1.password=m1
admin.associated.location.1.username=User_AL_01
admin.associated.location.1.password=password
customer.order.admin.1.username=customerorder.test
customer.order.admin.1.password=testorder123

#EM Location
em.location=Estate Manager

#User Maintenance
user.roles=Administrator,Manager - UK

#User Role Maintenance
special.functions.tab=Special Functions

# Customer Card Maintenance
issued.at=Enactor Store

#Gift Card Maintenance 
gift.card.type=Gift Card UK

# Location Maintenance
nearest.stores=Enactor Store
location.country=UK
bank.country=UK

# Reason Maintenance
transaction.discount.function.authorisation.code=Broadcast all
item.discount.function.authorisation.code=Broadcast all
transaction.void.function.authorisation.code=Broadcast all
item.void.function.authorisation.code=Broadcast all
receipt.return.function.authorisation.code=Broadcast all
item.return.function.authorisation.code=Broadcast all
price.override.function.authorisation.code=Broadcast all
mmg.sale.function.authorisation.code=Broadcast all
transaction.discount.parent.reason.id.1=10% Transaction Discount
transaction.discount.parent.reason.id.2=20% Transaction Discount
item.discount.parent.reason.id.1=10% Item Discount
item.discount.parent.reason.id.2=20% Item Discount
transaction.void.parent.reason.id.1=Item Faulty
transaction.void.parent.reason.id.2=Operator Error
item.void.parent.reason.id.1=Item Faulty
item.void.parent.reason.id.2=Operator Error
receipt.return.parent.reason.id.1=Damaged / Faulty (30 Days)
receipt.return.parent.reason.id.2=Not Wanted (10 Days)
item.return.parent.reason.id.1=Damaged / Faulty
item.return.parent.reason.id.2=Managers Discretion
price.override.parent.reason.id.1=Price Override Down
price.override.parent.reason.id.2=Price Override Up
mmg.sale.parent.reason.id.1=Faulty Barcode
mmg.sale.parent.reason.id.2=Not on file
item.discount.1=Employee 20% Discount
transaction.discount.1=Employee 20% Discount
transactions.type.list.1=Employee Retail Sale Transaction,Normal Retail Sale Transaction
transactions.type.list.2=Employee Retail Sale Transaction,Normal Retail Sale Transaction,Restaurant Sale Transaction
price.types.1=Minimum Sell Price
price.types.2=Minimum Sell Price,Fee
applicable.tenders=Cards UK,Cash UK,Cheques UK
witness.user.function.authorisation.code.1=Reserve stock
witness.skip.function.authorisation.code.1=Broadcast all
witness.skip.function.authorisation.code.2=Reserve stock
witness.user.function.authorisation.code.2=Broadcast all

# Voucher Serial Number Maintenance
voucher.type.1=Promo V
voucher.type.2=Credit Note

# Inbound Documents
transaction.id=

# Retail Transaction Archive Search
terminal.number=
transaction.number=

#Tender
drawer.limit=0

# Promotion Maintenance
region=United Kingdom

# Products
product.1=1
product.1.description=KAT VON D Eye Liner
style.size.product.1=A-5
style.size.product.1.description=A-5
style.size.product.1.size.range=Boys Shirts
style.size.product.1.size.option.1=Medium
style.colour.size.product.2=0DQJOJ4
style.colour.size.product.2.description=Tile Print Shorts
style.colour.size.product.2.size.range=Gc Shorts Skirts
style.colour.size.product.2.size.option.1=XL
style.colour.size.product.2.colour.range=Shorts And Skirts
style.colour.size.product.2.colour.option.1=Check

# Size Range
size.range.1=Mens Shirts

# Colour Range
colour.range.1=Mens Shirts

# Predefined Broadcast Maintenance
predefined.broadcast.id=AUTOMATION_BROADCAST
predefined.broadcast.name=Automation Broadcast
target.devices=AUT POS 1 @ Enactor Store
entities=Device,POS Terminal,User

#SAF-TFileGenerator
saf.t.start.date=today
saf.t.start.time=now -60 min
saf.t.end.date=today
saf.t.end.time=now
saf.t.location=Enactor Store Norway
saf.t.device.name=pos 1@ NO0001

# Clean Up Data
#===============
clean.up.gift.card.list=
clean.up.loyalty.card.list=
clean.up.customer.loyalty.account=1
clean.up.credit.note.number=
clean.up.credit.note.expiry.date=
clean.up.gift.voucher.serial.numbers.list=

#Inventory Buffer
description.selection.locale=English (UK)

#Inventory Buffer Dimension
dimension.column.index=Dimension - 10
dimension.column.index.value=10
dimension.column.index.copy=Dimension - 9
dimension.column.index.copy.value=9
dimension.column.index.edit=Dimension - 8
dimension.column.index.edit.value=8
description.selection.locale=English (UK)

#OfflineTokens
offline.tokens.client.id=pos1@0001.enactor-PosUpQC
waiting.time.seconds = "20"

#Restaurant Course Maintenance
restaurant.1=The Enactor Restaurant

#Digital Payment Configuration
digital.payment.configuration.payment.merchant.id=testQAMerchant

#Digital Payment Provider Configuration
digital.payment.provider.configuration.payment.merchant.id=testQAMerchant


sales.assistant.1.username=sales1
sales.assistant.1.password=1234
sales.assistant.2.username=sales2
sales.assistant.2.password=1234
sales.assistant.3.username=sales3
sales.assistant.3.password=12345
store.manager.2.username=manager
store.manager.2.password=1234
sales.assistant.no.location.username=SALES_NO_LOCATION
sales.assistant.no.location.password=1234

#Guided day Start 
guided.day.start.location=DK0032
guided.day.start.pay.point=Pay Point TA

#Guided Day End
guided.day.end.location=DK0032
