TRUNCATE TABLE CASHSESSIONS;
TRUNCATE TABLE CASHSESSIONTOTALS;
TRUNCATE TABLE CASHTRANSACTIONS;
TRUNCATE TABLE CASHTRANSACTIONITEMS;
TRUNCATE TABLE CASHTRANSACTIONITEMDENOMS;
TRUNCATE TABLE CASHTRANSACTIONTRACKEDITEMS;