# Values on POS UI
CHANGE_TEST_ASSISTANT_USERNAME=1001
CHANGE_TEST_ASSISTANT_PASSWORD=1001
CHANGE_TEST_PRODUCT=60001
CHANGE_TEST_PRODUCT_DESCRIPTION=Change Test
CHANGE_TEST_PRODUCT_PRICE=49.95

CHANGE_TEST_ABOVE_MINIMUM_DENOMINATION_AMOUNT=60.00
CHANGE_TEST_BELOW_MINIMUM_DENOMINATION_AMOUNT=50.00

# Values on Receipt
CHANGE_TEST_ABOVE_MINIMUM_DENOMINATION_TOTAL=49,95
CHANGE_TEST_ABOVE_MINIMUM_DENOMINATION_CHANGE_VALUE=10,05
CHANGE_TEST_BELOW_MINIMUM_DENOMINATION_TOTAL=49,95
CHANGE_TEST_BELOW_MINIMUM_DENOMINATION_OVERPAYMENT_VALUE=0,05
CHANGE_TEST_OVERPAYMENT_LABEL=Overpayment


