# AUT Connection Settings
autHostName=localhost
autPort=4099

# Mobile Device Settings
autMobilePlatformName=Android
autMobilePlatformVersion=14
autMobileDeviceUUID=R52YA0BTYCZ
autMobileDeviceName=Samsung A16
autMobileAppiumServerBaseURL=http://127.0.0.1:4723

# PDP Server
autMobilePDPHostName=localhost
autMobilePDPHostPort=39901
mobilePosDeviceId=POS_Shehan_Legacy@0001.enactor

# ChromeDriver
chromeDriverPath=D:\\chromedriver-win64\\chromedriver.exe

driver.type=org.openqa.selenium.chrome.ChromeDriver
driver.remote.debugging.port=localhost:9222
driver.skip.navigation.onInit=true

# Config Property Files
autConfigPropertyFileNames=posNextGen1024x768,webPos,androidReactThickPos
testDataPropertyFileNames=testData

# Terminal
TERMINAL_NUMBER=BIBG42M3TEPVG

# WebView
mobileWebView=WEBVIEW_com.enactor.pos

# Other Settings
autSimulateMouseMode=false
debug.enabled=true
enactor.tests.profile=uitest
