#########################################################################
# Enactor HTML Fixed POS Configuration File
############################### ##########################################
POS_APPLICATION_TYPE=HTML_FIXED
FULL_SCREEN_BROWSER_COMPONENT_NAME=JSON_THIN_CLIENT
APPLICATION_WINDOW_PREFIX=Point-of-Sale Application
CUSTOMER_VIEW_WINDOW_PREFIX=Point-of-Sale Customer View